# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push: 
    branches:
      - ananda23
      - patelde23
      - martinea23
      - deant23
      - millern23-4
      - master
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    name: Run Tests
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: diagnosis
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: 16.x

      # First install npm
      - name: install npm
        run: npm install

      # Then run jest command to run all the tests
      - name: run jest
        run: npm test

      # uploads coverage to codecov
      - uses: codecov/codecov-action@v2
        with:
          token: 6d4df5dd-dfbb-482b-ac48-0f7d73b74a56
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
